### ISSUE TITLE
Requests should be namespaced not prefixed

### ISSUE THREAD

**Issue by frankpde** [pwweb/artomator#4] opened 2019-06-29 11:15 UTC
Currently all validation requests are stored in one level with the prefix Validate. This causes issue in case a model is named identical in different namespaces.

E.g.:

App\Models\User
App\Models\Address
App\Models\User\Address

--> Issue ValidateAddress already exists

App\Models\User\Address is the link table for many to many and needs to be singular, else the eloquent method of assigning an address to the user does not work (tries to access column addresses_id instead of address_id.

**Comment by rabrowne85** [comment] 2019-06-29 12:38
Duplicate of #1

**Comment by frankpde** [comment] 2019-06-29 12:39
Issue was due to releases and now fixed in v0.1.1-beta

**Closed by rabrowne85** 2019-06-29 12:38 UTC
Labels: bug, enhancement
