### ISSUE TITLE
Missing default-schema.graphql

### ISSUE THREAD

**Issue by frankpde** [pwweb/artomator#58] opened 2021-04-05 15:26 UTC
On 
`php artisan vendor:publish --tag=artomator`

the following error is displayed:
`Can't locate path: </path/to/root/dir/vendor/pwweb/artomator/src/../../../nuwave/lighthouse/assets/default-schema.graphql>`

This is on a clean install of latest laravel & artomator.

**Comment by rabrowne85** [comment] 2021-04-05 21:34
Duplicate of #36 and #55.

Fixed in master. Will check if new version needed.

**Comment by rabrowne85** [comment] 2021-04-06 07:54
Confirm fixed in the master branch. Will be pulled into the next release.

See 5c192395d682c85281544751abc185e9e9579f5a

**Comment by frankpde** [comment] 2021-04-06 09:28
> Duplicate of #36 and #55.
> 
> Fixed in master. Will check if new version needed.

Not sure it is a duplicate. The error message in #36 and #55 relate to the schema.graphql of the actual implementation, whereas above is on a clean install and not finding the default-schema.graphql out of the lighthouse package. Maybe it was moved to a different location in that package and hence the artomator publish command tries to copy a non-existing file.

**Comment by rabrowne85** [comment] 2021-04-06 09:35
They are related, as they are what happens when the lighthouse schema isn't copied. The root of the problem is this issue though that the file moved location in the sub-package. I've already put a fix into the master as per the previous comment, it's just not tagged to a version yet so doesn't get pulled in on the standard composer require unless you specify the master branch.

**Comment by rabrowne85** [comment] 2021-04-10 12:15
Fixed in 92479fdd0c37dcb4fd97ebe72e0dbdcea92339cc

**Closed by rabrowne85** 2021-04-10 12:15 UTC
Labels: duplicate
